/**
 * Client Dashboard (Phase F · Sprint F1). Everything is powered by existing read
 * models via `loadWorkspaceDashboard()` — workspace health, missions, reports,
 * automations, approvals. Thin server component; graceful empty states.
 */

import Link from "next/link";
import { Badge, EmptyState } from "@brightloop/ui";
import { loadWorkspaceDashboard } from "@/lib/workspace-data";
import styles from "./pages.module.css";

export default async function DashboardPage() {
  const data = await loadWorkspaceDashboard();
  if (data === null) return <EmptyState icon="lock" title="Session expired" body="Please sign in again to view your workspace." />;

  if (data.workspace === null) {
    return (
      <>
        <div className={styles.pageHead}><div><h1 className={styles.pageTitle}>Welcome to Auxion</h1><p className={styles.pageSub}>Your workspace is being set up. Strategy, plans, automations and reports will appear here.</p></div></div>
        <EmptyState icon="rocket" title="No workspace yet" body="Once your transformation workspace is provisioned, your dashboard will populate automatically." />
      </>
    );
  }

  const activeMissions = data.missions.filter((m) => m.status === "running" || m.status === "planning" || m.status === "resuming");
  const waiting = data.missions.filter((m) => m.status === "waiting_for_approval");
  const latestReports = data.reports.slice(0, 4);

  return (
    <>
      <div className={styles.pageHead}>
        <div><h1 className={styles.pageTitle}>{data.workspace.title}</h1><p className={styles.pageSub}>Your transformation at a glance{data.health.period ? ` · ${data.health.period}` : ""}</p></div>
        <Link href="/workspace/reports" className={styles.sectionLink}>View reports →</Link>
      </div>

      <div className={styles.metricGrid}>
        <div className={styles.metric}><span className={styles.metricLabel}>Workspace health</span><span className={styles.metricValue}>{data.health.health ?? "—"}<small>{data.health.health !== null ? "/100" : ""}</small></span></div>
        <div className={styles.metric}><span className={styles.metricLabel}>Active missions</span><span className={styles.metricValue}>{data.ops.activeMissions}</span></div>
        <div className={styles.metric}><span className={styles.metricLabel}>Awaiting approval</span><span className={styles.metricValue}>{data.ops.waitingApprovals}</span></div>
        <div className={styles.metric}><span className={styles.metricLabel}>Reports</span><span className={styles.metricValue}>{data.counts.reports}</span></div>
        <div className={styles.metric}><span className={styles.metricLabel}>Automations</span><span className={styles.metricValue}>{data.counts.automations}</span></div>
        <div className={styles.metric}><span className={styles.metricLabel}>Confidence</span><span className={styles.metricValue}>{data.health.confidence ?? "—"}<small>{data.health.confidence !== null ? "%" : ""}</small></span></div>
      </div>

      <div className={styles.grid2}>
        <div>
          <section className={styles.section}>
            <div className={styles.sectionHead}><span className={styles.sectionTitle}>Mission progress</span><Link href="/workspace/ai-team" className={styles.sectionLink}>AI Team →</Link></div>
            {activeMissions.length === 0 ? <EmptyState icon="sparkles" title="No active missions" body="Start a mission from the AI Team to orchestrate your specialists." />
              : <div className={styles.list}>{activeMissions.slice(0, 5).map((m) => (
                  <Link key={m.id} href={`/workspace/missions/${m.id}`} className={styles.row}>
                    <div className={styles.rowMain}><div className={styles.rowTitle}>{m.title}</div><div className={styles.rowMeta}>{m.status.replace(/_/g, " ")}</div></div>
                    <div className={styles.rowRight}><div className={styles.progressTrack}><div className={styles.progressFill} style={{ width: `${m.progress}%` }} /></div><Badge status={m.status}>{m.progress}%</Badge></div>
                  </Link>))}</div>}
          </section>

          <section className={styles.section}>
            <div className={styles.sectionHead}><span className={styles.sectionTitle}>Latest reports</span><Link href="/workspace/reports" className={styles.sectionLink}>All reports →</Link></div>
            {latestReports.length === 0 ? <EmptyState icon="line-chart" title="No reports yet" body="Executive reports generated by your AI team will appear here." />
              : <div className={styles.list}>{latestReports.map((r) => (
                  <Link key={r.id} href="/workspace/reports" className={styles.row}>
                    <div className={styles.rowMain}><div className={styles.rowTitle}>{r.title}</div><div className={styles.rowMeta}>{r.kind.replace(/_/g, " ")} · {r.metricCount} metrics · {r.insightCount} insights</div></div>
                    <div className={styles.rowRight}><Badge status={r.status}>{r.status}</Badge></div>
                  </Link>))}</div>}
          </section>
        </div>

        <div>
          <section className={styles.section}>
            <div className={styles.sectionHead}><span className={styles.sectionTitle}>Upcoming approvals</span><Link href="/workspace/approvals" className={styles.sectionLink}>Review →</Link></div>
            {waiting.length === 0 ? <EmptyState icon="check-circle" title="Nothing to approve" body="You’re all caught up." />
              : <div className={styles.list}>{waiting.slice(0, 6).map((m) => (
                  <Link key={m.id} href="/workspace/approvals" className={styles.row}><div className={styles.rowMain}><div className={styles.rowTitle}>{m.title}</div><div className={styles.rowMeta}>Awaiting your decision</div></div><Badge tone="warning">Review</Badge></Link>))}</div>}
          </section>

          <section className={styles.section}>
            <div className={styles.sectionHead}><span className={styles.sectionTitle}>Quick actions</span></div>
            <div className={styles.list}>
              <Link href="/workspace/reports?generate=1" className={styles.row}><div className={styles.rowMain}><div className={styles.rowTitle}>Generate a report</div><div className={styles.rowMeta}>Executive summary</div></div></Link>
              <Link href="/workspace/ai-team?mission=1" className={styles.row}><div className={styles.rowMain}><div className={styles.rowTitle}>Start a mission</div><div className={styles.rowMeta}>AI orchestration</div></div></Link>
              <Link href="/workspace/projects" className={styles.row}><div className={styles.rowMain}><div className={styles.rowTitle}>Browse projects</div><div className={styles.rowMeta}>{data.workspaces.length} project(s)</div></div></Link>
            </div>
          </section>
        </div>
      </div>
    </>
  );
}
