/* =============================================================================
 * Integration Platform — Certification Reporter (F4.8). PURE.
 *
 * Renders an IntegrationCertificationReport into a deterministic markdown document
 * (the human-readable certification report) and a stable JSON snapshot. No io — the
 * caller (a build-time script) writes the strings to disk. Deterministic: given the
 * same report it always produces byte-identical output.
 * ========================================================================== */

import type { IntegrationCertificationReport } from "./certify.js";

const yesNo = (b: boolean): string => (b ? "✓" : "—");
const pass = (b: boolean): string => (b ? "PASS" : "FAIL");

/** Render the full certification report as markdown. */
export function renderCertificationMarkdown(report: IntegrationCertificationReport): string {
  const L: string[] = [];
  L.push(`# Integration Platform — Certification Report`);
  L.push("");
  L.push(`**Subject:** ${report.subject}  `);
  L.push(`**Generated:** ${report.generatedAt} (deterministic, offline)  `);
  L.push(`**Result:** ${report.ok ? "✅ CERTIFIED — READY FOR REVIEW" : "❌ BLOCKED — defects found"}`);
  L.push("");
  L.push(`> Generated by the automated certification harness`);
  L.push(`> (\`@brightloop/data\` · \`integration/certification/certify.ts\`). Re-run with`);
  L.push(`> \`pnpm -w build && node application/scripts/certify-integration.mjs\`.`);
  L.push("");

  L.push(`## 1. Totals`);
  L.push("");
  L.push(`| Metric | Value |`);
  L.push(`| --- | --- |`);
  L.push(`| Registry connectors | ${report.totals.connectors} |`);
  L.push(`| Installable (available) connectors | ${report.totals.availableConnectors} |`);
  L.push(`| Catalogue-only examples | ${report.totals.catalogueExamples} |`);
  L.push(`| Connector families | ${report.totals.families} |`);
  L.push(`| Live adapters composed | ${report.totals.adapters} |`);
  L.push(`| Certified capabilities | ${report.totals.capabilities} |`);
  L.push(`| Orphan capabilities | ${report.totals.orphanCapabilities} |`);
  L.push(`| Undeclared handlers | ${report.totals.missingHandlers} |`);
  L.push(`| Duplicate registrations | ${report.totals.duplicateRegistrations} |`);
  L.push(`| Orphan adapters | ${report.totals.orphanAdapters} |`);
  L.push("");

  L.push(`## 2. Certification areas`);
  L.push("");
  L.push(`| Area | Result | Passed | Failed | Notes |`);
  L.push(`| --- | --- | --- | --- | --- |`);
  for (const a of report.areas) {
    L.push(`| ${a.name} | ${pass(a.ok)} | ${a.passed} | ${a.failed} | ${a.notes.join("; ")} |`);
  }
  L.push("");

  L.push(`## 3. Certified connector families`);
  L.push("");
  L.push(`| Family | Connectors | Capabilities | Connector ids |`);
  L.push(`| --- | --- | --- | --- |`);
  for (const f of report.families) {
    L.push(`| ${f.family} | ${f.connectors} | ${f.capabilities} | ${f.connectorIds.join(", ")} |`);
  }
  L.push("");

  L.push(`## 4. Connector certification matrix`);
  L.push("");
  L.push(`Columns: **Inv**=invocation (execute) · **Authz**=authorization funnel · **Hlth**=health · **Val**=connection validation · **Poll**=polling · **Hook**=webhook · **OAuth**=OAuth wiring · **Aud**=audit.`);
  L.push("");
  L.push(`| Connector | Family | Auth | Triggers | Caps | Inv | Authz | Hlth | Val | Poll | Hook | OAuth | Aud | Result |`);
  L.push(`| --- | --- | --- | --- | --- | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | --- |`);
  for (const c of report.connectors) {
    if (!c.available) continue;
    L.push(
      `| ${c.name} (\`${c.connectorId}\`) | ${c.family} | ${c.authMethod} | ${c.triggerKinds.join("+") || "none"} | ${c.capabilityCount} | ` +
      `${yesNo(c.invocation)} | ${yesNo(c.authorization)} | ${yesNo(c.health)} | ${yesNo(c.connectionValidation)} | ${yesNo(c.polling)} | ${yesNo(c.webhook)} | ${yesNo(c.oauth)} | ${yesNo(c.audit)} | ${pass(c.ok)} |`,
    );
  }
  L.push("");

  const examples = report.connectors.filter((c) => !c.available);
  if (examples.length > 0) {
    L.push(`### Catalogue-only examples (not installable — no adapter, by design)`);
    L.push("");
    L.push(`| Connector | Family | Auth | Result |`);
    L.push(`| --- | --- | --- | --- |`);
    for (const c of examples) L.push(`| ${c.name} (\`${c.connectorId}\`) | ${c.family} | ${c.authMethod} | ${pass(c.ok)} |`);
    L.push("");
  }

  L.push(`## 5. Capability certification`);
  L.push("");
  const failedCaps = report.capabilities.filter((c) => !c.ok);
  L.push(`- Total capabilities certified: **${report.capabilities.length}**`);
  L.push(`- Every declared capability has: descriptor · operation · adapter · handler.`);
  L.push(`- Orphan capabilities (declared, unhandled): **${report.totals.orphanCapabilities}**`);
  L.push(`- Undeclared handlers (supported, not declared): **${report.totals.missingHandlers}**`);
  L.push(`- Failed capability rows: **${failedCaps.length}**`);
  if (failedCaps.length > 0) {
    L.push("");
    L.push(`| Connector | Capability | Operation | Issues |`);
    L.push(`| --- | --- | --- | --- |`);
    for (const c of failedCaps) L.push(`| ${c.connectorId} | ${c.capabilityKey} | ${c.operation} | ${c.issues.join("; ")} |`);
  }
  L.push("");

  L.push(`## 6. Health vocabulary`);
  L.push("");
  L.push(`Every connector reports one of the shared, normalized health levels — no connector-specific state leaks:`);
  L.push("");
  L.push(report.healthVocabulary.map((h) => `\`${h}\``).join(" · "));
  L.push("");
  L.push(`Provider-specific reasons (\`connected\`, \`disconnected\`, \`expired\`, \`permission_missing\`, \`rate_limited\`, \`configuration_error\`) are carried in the snapshot \`detail\` only, and map onto these levels uniformly across all six families.`);
  L.push("");

  L.push(`## 7. Certification exceptions (documented, intentional)`);
  L.push("");
  for (const e of report.exceptions) L.push(`- ${e}`);
  L.push("");
  L.push(`These are approved design decisions inherited from F4.1–F4.7, not defects; they do not fail certification.`);
  L.push("");

  return L.join("\n");
}

/** A stable JSON snapshot of the report (2-space indented, trailing newline). */
export function renderCertificationJson(report: IntegrationCertificationReport): string {
  return `${JSON.stringify(report, null, 2)}\n`;
}
